[package]
name = "node"
edition.workspace = true
version.workspace = true

[dependencies]
abi = { workspace = true }
borsh = { workspace = true }
commonware-codec = { workspace = true }
commonware-cryptography = { workspace = true }
commonware-runtime = { workspace = true }
commonware-storage = { workspace = true }
commonware-utils = { workspace = true }
host = { workspace = true }
keyscheme = { workspace = true }
state = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
fixture-modules = { path = "../fixtures/modules" }
fixture-probe = { path = "../fixtures/probe" }
fixture-relay = { path = "../fixtures/relay" }
fixture-valset = { path = "../fixtures/valset" }
keyscheme = { workspace = true, features = ["testkit"] }
tempfile = { workspace = true }
